const PREFIX_CARD = 'debitCardApi/';

export const GET_CARD_DETAILS_SUCCESS = `${PREFIX_CARD}SUCCESS/GET_CARD_DETAILS_SUCCESS`;
export const GET_CARD_DETAILS_REQUEST = `${PREFIX_CARD}REQUEST/GET_CARD_DETAILS_REQUEST`;
export const GET_CARD_DETAILS_FAILURE = `${PREFIX_CARD}FAILURE/GET_CARD_DETAILS_FAILURE`;

export const UPDATE_DEBIT_CARD_LIMIT = `${PREFIX_CARD}UPDATE/UPDATE_DEBIT_CARD_LIMIT`;
